---@module "treesitter-langs"
---@author Conner Ohnesorge
---@license WTFPL

return {
        "c",
        "cpp",
        "go",
        "lua",
        "python",
        "rust",
        "tsx",
        "typescript",
        "vimdoc",
        "vim",
        "c_sharp",
        "astro",
        "ninja",
        "bash",
        "css",
        "rst",
        "toml",
        "markdown",
        "markdown_inline",
        "proto",
        "printf",
        "json",
        "php",
        "regex",
        "sql",
        "yaml",
        "html",
        "javascript",
        "jsonc",
        "zig",
        "svelte",
        "nix",
        "ocamllex",
        "ocaml",
        "luadoc",
        "kotlin",
        "jsdoc",
        "go",
        "dockerfile",
        "asm",
        "arduino",
        "bash",
        "cmake",
        -- "git_rebase",
        -- "git_config",
        -- "gitignore",
        "gitcommit",
        "latex",
        "requirements",
        "todotxt",
        "verilog",
        "vhs",
        "yaml",
        "templ",
}
