name: Test Neovim

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-nvim:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install Neovim
      run: |
        # move root of the the repository to ~/.config/nvim
        cp -r . ~/.config/nvim
    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: v0.4.3

    - name: Run tests
      run: |
          sh ./scripts/test.sh
